# Generated by Django 3.0.5 on 2020-05-18 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilitiesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2000)),
                ('slug', models.CharField(default='slimak', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('equipment', models.TextField(max_length=5000)),
                ('current_exp', models.IntegerField(default=0)),
                ('total_exp', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('notes', models.TextField(default='NOTATKI', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stats', models.TextField(max_length=2000)),
                ('skills', models.TextField(max_length=2000)),
                ('abilities', models.TextField(max_length=2000)),
                ('equipment', models.TextField(max_length=2000)),
                ('next_profession', models.TextField(max_length=2000)),
                ('is_starting', models.BooleanField(default=True)),
                ('slug', models.CharField(default='slimak', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RaceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=2000)),
                ('slug', models.CharField(max_length=30)),
                ('skills', models.TextField(max_length=2000)),
                ('abilities', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2000)),
                ('is_basic', models.BooleanField(default=True)),
                ('slug', models.CharField(default='slimak', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StatsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('short', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=500)),
                ('is_secondary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VitalityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_1_3', models.IntegerField()),
                ('v_4_6', models.IntegerField()),
                ('v_7_9', models.IntegerField()),
                ('v_10', models.IntegerField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.RaceModel')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.StatsModel')),
            ],
        ),
        migrations.CreateModel(
            name='StartingStatsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.IntegerField(default=20)),
                ('bonus', models.IntegerField(default=2)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.RaceModel')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.StatsModel')),
            ],
        ),
        migrations.CreateModel(
            name='SkillsProfessionMiddle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.ProfessionModel')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.SkillsModel')),
            ],
        ),
        migrations.AddField(
            model_name='skillsmodel',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.StatsModel'),
        ),
        migrations.CreateModel(
            name='RandomAbilityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_range', models.CharField(max_length=10)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.AbilitiesModel')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.RaceModel')),
            ],
        ),
        migrations.CreateModel(
            name='HumanStartingProfession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_range', models.CharField(max_length=10)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.ProfessionModel')),
            ],
        ),
        migrations.CreateModel(
            name='HalflingStartingProfession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_range', models.CharField(max_length=10)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.ProfessionModel')),
            ],
        ),
        migrations.CreateModel(
            name='FateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_1_4', models.IntegerField()),
                ('f_5_7', models.IntegerField()),
                ('f_8_10', models.IntegerField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.RaceModel')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.StatsModel')),
            ],
        ),
        migrations.CreateModel(
            name='ElfStartingProfession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_range', models.CharField(max_length=10)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.ProfessionModel')),
            ],
        ),
        migrations.CreateModel(
            name='DwarfStartingProfession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_range', models.CharField(max_length=10)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.ProfessionModel')),
            ],
        ),
        migrations.CreateModel(
            name='CharactersStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.IntegerField()),
                ('bonus', models.IntegerField()),
                ('max_bonus', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.CharacterModel')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.StatsModel')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.IntegerField(default=0)),
                ('is_developed', models.BooleanField(default=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.CharacterModel')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.SkillsModel')),
            ],
        ),
        migrations.AddField(
            model_name='charactermodel',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.ProfessionModel'),
        ),
        migrations.AddField(
            model_name='charactermodel',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.RaceModel'),
        ),
        migrations.AddField(
            model_name='charactermodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CharacterAbilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.CharField(blank=True, max_length=50, null=True)),
                ('stat_bonus', models.IntegerField(blank=True, null=True)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.AbilitiesModel')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.CharacterModel')),
                ('stat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warhammer.StatsModel')),
            ],
        ),
    ]
