# Generated by Django 2.1.4 on 2019-03-10 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_1_4', models.IntegerField()),
                ('f_5_7', models.IntegerField()),
                ('f_8_10', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RaceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='StartingStatsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.IntegerField(default=20)),
                ('bonus', models.IntegerField(default=2)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.RaceModel')),
            ],
        ),
        migrations.CreateModel(
            name='StatsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('short', models.CharField(max_length=5)),
                ('description', models.TextField(max_length=500)),
                ('is_secondary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VitalityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_1_3', models.IntegerField()),
                ('v_4_6', models.IntegerField()),
                ('v_7_9', models.IntegerField()),
                ('v_10', models.IntegerField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.RaceModel')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.StatsModel')),
            ],
        ),
        migrations.AddField(
            model_name='startingstatsmodel',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.StatsModel'),
        ),
    ]
