# Generated by Django 2.1.4 on 2019-03-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racemodel',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='statsmodel',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='statsmodel',
            name='short',
            field=models.CharField(max_length=10),
        ),
    ]
