# Generated by Django 3.0.7 on 2020-07-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0002_delete_skillsprofessionmiddle'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilitiesmodel',
            name='description_en',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='abilitiesmodel',
            name='name_en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='professionmodel',
            name='name_en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='racemodel',
            name='description_en',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='racemodel',
            name='name_en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='skillsmodel',
            name='description_en',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='skillsmodel',
            name='name_en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='statsmodel',
            name='description_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='statsmodel',
            name='name_en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='statsmodel',
            name='short_en',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
