# Generated by Django 2.1.4 on 2019-03-10 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0002_auto_20190310_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatemodel',
            name='race',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='warhammer.RaceModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fatemodel',
            name='stat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='warhammer.StatsModel'),
            preserve_default=False,
        ),
    ]
