# Generated by Django 3.0.7 on 2020-07-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0003_auto_20200721_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionmodel',
            name='equipment_en',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
