# Generated by Django 2.1.4 on 2019-03-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0003_auto_20190310_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='racemodel',
            name='slug',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
