# Generated by Django 2.1.4 on 2019-03-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0004_racemodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stats', models.TextField(max_length=2000)),
                ('skills', models.TextField(max_length=2000)),
                ('abilities', models.TextField(max_length=2000)),
                ('equipment', models.TextField(max_length=2000)),
                ('next_profession', models.TextField(max_length=2000)),
                ('is_starting', models.BooleanField(default=True)),
            ],
        ),
    ]
