# Generated by Django 2.1.4 on 2019-03-12 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0006_skillsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsProfessionMiddle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.ProfessionModel')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.SkillsModel')),
            ],
        ),
    ]
