# Generated by Django 2.1.4 on 2019-03-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0007_skillsprofessionmiddle'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionmodel',
            name='slug',
            field=models.CharField(default='slimak', max_length=50),
        ),
    ]
