# Generated by Django 2.1.4 on 2019-03-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0008_professionmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsmodel',
            name='is_basic',
            field=models.BooleanField(default=True),
        ),
    ]
