# Generated by Django 2.1.4 on 2019-03-14 08:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0009_skillsmodel_is_basic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step1Model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('WW', models.IntegerField()),
                ('US', models.IntegerField()),
                ('ZR', models.IntegerField()),
                ('K', models.IntegerField()),
                ('Odp', models.IntegerField()),
                ('Int', models.IntegerField()),
                ('SW', models.IntegerField()),
                ('Vit', models.IntegerField()),
                ('PP', models.IntegerField()),
                ('PROF', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Step2Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('equipment', models.TextField(max_length=5000)),
                ('exp', models.IntegerField(default=100)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.ProfessionModel')),
            ],
        ),
    ]
