# Generated by Django 2.1.4 on 2019-03-17 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0011_dwarfstartingprofession_elfstartingprofession_halflingstartingprofession_humanstartingprofession'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=123)),
                ('name', models.CharField(max_length=50)),
                ('equipment', models.TextField(max_length=5000)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.ProfessionModel')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.CharField(blank=True, max_length=50)),
                ('level', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.CharacterModel')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.SkillsModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='step2model',
            name='profession',
        ),
        migrations.DeleteModel(
            name='Step2Model',
        ),
    ]
