# Generated by Django 2.1.4 on 2019-03-17 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0012_auto_20190317_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharactersStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.IntegerField()),
                ('bonus', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='charactermodel',
            name='current_exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactermodel',
            name='race',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='warhammer.RaceModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charactermodel',
            name='total_exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characterskills',
            name='is_developed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='racemodel',
            name='abilities',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racemodel',
            name='skills',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charactersstats',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.CharacterModel'),
        ),
        migrations.AddField(
            model_name='charactersstats',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.StatsModel'),
        ),
    ]
