# Generated by Django 2.1.4 on 2019-03-18 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0013_auto_20190318_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilitiesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterAbilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_bonus', models.IntegerField(blank=True)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.AbilitiesModel')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.CharacterModel')),
                ('stat', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='warhammer.StatsModel')),
            ],
        ),
        migrations.AddField(
            model_name='charactersstats',
            name='max_bonus',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
