# Generated by Django 2.1.4 on 2019-03-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0015_auto_20190319_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterabilities',
            name='bonus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='step1model',
            name='string',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
