# Generated by Django 2.1.4 on 2019-03-20 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0016_auto_20190320_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomAbilityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_range', models.CharField(max_length=10)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.AbilitiesModel')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.RaceModel')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='characterskills',
            unique_together={('skill', 'bonus', 'character')},
        ),
    ]
