# Generated by Django 2.1.4 on 2019-03-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0017_auto_20190320_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilitiesmodel',
            name='slug',
            field=models.CharField(default='slimak', max_length=50),
        ),
        migrations.AddField(
            model_name='skillsmodel',
            name='slug',
            field=models.CharField(default='slimak', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='characterabilities',
            unique_together={('ability', 'bonus', 'character')},
        ),
    ]
