# Generated by Django 2.1.4 on 2019-03-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0018_auto_20190322_1120'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characterabilities',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='characterskills',
            unique_together=set(),
        ),
    ]
