# Generated by Django 2.1.4 on 2019-03-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0019_auto_20190325_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactermodel',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
