# Generated by Django 2.1.4 on 2019-03-28 19:15

from django.db import migrations

def create_profiles(apps, schema_editor):
    User = apps.get_model(app_label='auth', model_name='User')
    Profile = apps.get_model("warhammer", "Profile")
    for u in User.objects.all():
        if not hasattr(u, 'profile'):
            Profile.objects.create(user=u)
            u.save()

class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0021_profile'),
    ]

    operations = [
        migrations.RunPython(create_profiles)
    ]
