# Generated by Django 2.1.4 on 2019-03-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0022_auto_20190328_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
