# Generated by Django 2.1.4 on 2019-03-28 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0023_auto_20190328_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
