# Generated by Django 2.1.7 on 2019-05-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0025_auto_20190331_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactermodel',
            name='notes',
            field=models.TextField(default='NOTATKI', max_length=5000),
        ),
    ]
