# Generated by Django 2.1.7 on 2019-06-03 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0027_gamemodel_mapmodel_messagesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPCModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('WW', models.IntegerField()),
                ('US', models.IntegerField()),
                ('notes', models.TextField(max_length=1000)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammer.GameModel')),
            ],
        ),
    ]
