# Generated by Django 3.0.5 on 2020-05-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0028_npcmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Step1Model',
        ),
    ]
