# Generated by Django 3.0.5 on 2020-05-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0029_delete_step1model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapmodel',
            name='game',
        ),
        migrations.RemoveField(
            model_name='messagesmodel',
            name='game',
        ),
        migrations.RemoveField(
            model_name='npcmodel',
            name='game',
        ),
        migrations.DeleteModel(
            name='GameModel',
        ),
        migrations.DeleteModel(
            name='MapModel',
        ),
        migrations.DeleteModel(
            name='MessagesModel',
        ),
        migrations.DeleteModel(
            name='NPCModel',
        ),
    ]
