# Generated by Django 3.0.5 on 2020-05-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wh_chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapmodel',
            name='counter',
        ),
    ]
