# Generated by Django 3.0.5 on 2020-05-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wh_chat', '0002_remove_mapmodel_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmodel',
            name='columns',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='mapmodel',
            name='rows',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='mapmodel',
            name='tokens',
            field=models.PositiveIntegerField(default=13),
        ),
    ]
